export default function PreloadFonts() {
    return (
        <>
            <link
              rel="preload"
              href="../public/fonts/apercu-medium-pro.ttf"
              as="font"
              type="font/ttf"
              crossOrigin="anonymous"
            />
            <link
              rel="preload"
              href="../public/fonts/apercu-medium-pro.woff"
              as="font"
              type="font/woff"
              crossOrigin="anonymous"
            />
            <link
              rel="preload"
              href="../public/fonts/apercu-medium-pro.woff2"
              as="font"
              type="font/woff2"
              crossOrigin="anonymous"
            />
            <link
              rel="preload"
              href="../public/fonts/apercu-bold-pro.ttf"
              as="font"
              type="font/ttf"
              crossOrigin="anonymous"
            />
            <link
              rel="preload"
              href="../public/fonts/apercu-bold-pro.woff"
              as="font"
              type="font/woff"
              crossOrigin="anonymous"
            />
            <link
              rel="preload"
              href="../public/fonts/apercu-bold-pro.woff2"
              as="font"
              type="font/woff2"
              crossOrigin="anonymous"
            />
            <link
              rel="preload"
              href="../public/fonts/apercu-regular-pro.ttf"
              as="font"
              type="font/ttf"
              crossOrigin="anonymous"
            />
            <link
              rel="preload"
              href="../public/fonts/apercu-regular-pro.woff"
              as="font"
              type="font/woff"
              crossOrigin="anonymous"
            />
            <link
              rel="preload"
              href="../public/fonts/apercu-regular-pro.woff2"
              as="font"
              type="font/woff2"
              crossOrigin="anonymous"
            />
        </>
    )
}